/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.rentajet.base;

import de.rentajet.frames.AnredeInfo;
import de.rentajet.frames.BenutzerInfo;
import de.rentajet.frames.BenutzergruppeInfo;
import de.rentajet.frames.FirmaInfo;
import de.rentajet.frames.FlugzeugInfo;
import de.rentajet.frames.FlugzeugkostenInfo;
import de.rentajet.frames.FlugzeugtypInfo;
import de.rentajet.frames.KundeInfo;
import de.rentajet.frames.KundenberaterInfo;
import de.rentajet.frames.MitarbkundeInfo;
import de.rentajet.frames.OrtInfo;
import de.rentajet.frames.StaatInfo;
import de.rentajet.frames.TriebwerkartInfo;
import de.rentajet.frames.ZahlungsbedingungInfo;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Petersen
 */
public class FrmMain extends javax.swing.JFrame {

	/**
	 * Creates new form FrmMain
	 */
	public FrmMain() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	@SuppressWarnings({"unchecked", "deprecation"})
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenu3 = new javax.swing.JMenu();
    jMenuBar2 = new javax.swing.JMenuBar();
    jMenu4 = new javax.swing.JMenu();
    jMenu5 = new javax.swing.JMenu();
    jMenu6 = new javax.swing.JMenu();
    jMenu9 = new javax.swing.JMenu();
    jMenuItem13 = new javax.swing.JMenuItem();
    jPanel1 = new javax.swing.JPanel();
    jToolBar1 = new javax.swing.JToolBar();
    jButton1 = new javax.swing.JButton();
    jSeparator4 = new javax.swing.JToolBar.Separator();
    jButton2 = new javax.swing.JButton();
    jSeparator5 = new javax.swing.JToolBar.Separator();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jSeparator6 = new javax.swing.JToolBar.Separator();
    jButton8 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton10 = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    jSeparator7 = new javax.swing.JToolBar.Separator();
    jButton12 = new javax.swing.JButton();
    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel2 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jButton17 = new javax.swing.JButton();
    jButton18 = new javax.swing.JButton();
    jButton19 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jButton20 = new javax.swing.JButton();
    jButton21 = new javax.swing.JButton();
    jButton22 = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jButton24 = new javax.swing.JButton();
    jButton25 = new javax.swing.JButton();
    jButton26 = new javax.swing.JButton();
    jButton27 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jButton28 = new javax.swing.JButton();
    jButton29 = new javax.swing.JButton();
    jButton30 = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jButton31 = new javax.swing.JButton();
    jButton32 = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenuItem4 = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    jMenuItem5 = new javax.swing.JMenuItem();
    jSeparator2 = new javax.swing.JPopupMenu.Separator();
    jMenuItem6 = new javax.swing.JMenuItem();
    jMenuItem7 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem8 = new javax.swing.JMenuItem();
    jSeparator3 = new javax.swing.JPopupMenu.Separator();
    jMenuItem9 = new javax.swing.JMenuItem();
    jMenuItem10 = new javax.swing.JMenuItem();
    jMenuItem11 = new javax.swing.JMenuItem();
    jMenuItem12 = new javax.swing.JMenuItem();
    jMenu7 = new javax.swing.JMenu();
    jMenu10 = new javax.swing.JMenu();
    jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
    jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
    jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
    jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
    jMenu8 = new javax.swing.JMenu();
    jMenuItem14 = new javax.swing.JMenuItem();
    jMenuItem15 = new javax.swing.JMenuItem();

    jMenu3.setText("jMenu3");

    jMenu4.setText("File");
    jMenuBar2.add(jMenu4);

    jMenu5.setText("Edit");
    jMenuBar2.add(jMenu5);

    jMenu6.setText("jMenu6");

    jMenu9.setText("jMenu9");

    jMenuItem13.setText("jMenuItem13");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("RentAJet");
    setMinimumSize(new java.awt.Dimension(800, 600));
    setName("frmMain"); // NOI18N

    jPanel1.setLayout(new java.awt.BorderLayout());

    jToolBar1.setRollover(true);

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/computer_24st.gif"))); // NOI18N
    jButton1.setFocusable(false);
    jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton1.setName("btnAbmelden"); // NOI18N
    jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton1);
    jToolBar1.add(jSeparator4);

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/drucker_24st.gif"))); // NOI18N
    jButton2.setFocusable(false);
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton2.setName("btnDrucken"); // NOI18N
    jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton2);
    jToolBar1.add(jSeparator5);

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/vcrbegin_24st.gif"))); // NOI18N
    jButton3.setFocusable(false);
    jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton3.setName("btnErster"); // NOI18N
    jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton3);

    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/vcrback_24st.gif"))); // NOI18N
    jButton4.setFocusable(false);
    jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton4.setName("btnVorheriger"); // NOI18N
    jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton4);

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/vcrforward_24st.gif"))); // NOI18N
    jButton5.setFocusable(false);
    jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton5.setName("btnNaechster"); // NOI18N
    jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton5);

    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/vcrend_24st.gif"))); // NOI18N
    jButton6.setFocusable(false);
    jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton6.setName("btnLetzter"); // NOI18N
    jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton6);

    jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/row_24st.gif"))); // NOI18N
    jButton7.setFocusable(false);
    jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton7.setName("btnSuche"); // NOI18N
    jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton7);
    jToolBar1.add(jSeparator6);

    jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/save_24st.gif"))); // NOI18N
    jButton8.setFocusable(false);
    jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton8.setName("btnSpeichern"); // NOI18N
    jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton8);

    jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/erase2_24st.gif"))); // NOI18N
    jButton9.setFocusable(false);
    jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton9.setName("btnAbbrechen"); // NOI18N
    jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton9);

    jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/deleterow_24st.gif"))); // NOI18N
    jButton10.setFocusable(false);
    jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton10.setName("btnLöschen"); // NOI18N
    jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton10);

    jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/partie_24st.gif"))); // NOI18N
    jButton11.setFocusable(false);
    jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton11.setName("btnAktualisieren"); // NOI18N
    jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton11);
    jToolBar1.add(jSeparator7);

    jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/rentajet/bilder/24/st/schrank1_24st.gif"))); // NOI18N
    jButton12.setFocusable(false);
    jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton12.setName("btnArchiv"); // NOI18N
    jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton12);

    jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

    jPanel2.setName("pnlMenu"); // NOI18N
    jPanel2.setLayout(new java.awt.BorderLayout());

    jPanel5.setLayout(new java.awt.GridLayout(25, 1));

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Stammdaten");
    jPanel5.add(jLabel1);

    jButton17.setText("Anrede");
    jButton17.setName("btnAnrede"); // NOI18N
    jButton17.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton17ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton17);

    jButton18.setText("Ort");
    jButton18.setName("btnOrt"); // NOI18N
    jButton18.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton18ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton18);

    jButton19.setText("Staat");
    jButton19.setToolTipText("");
    jButton19.setName("btnStaat"); // NOI18N
    jButton19.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton19ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton19);

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Allgemein");
    jPanel5.add(jLabel2);

    jButton20.setText("Firmenparameter");
    jButton20.setName("btnFirma"); // NOI18N
    jButton20.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton20ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton20);

    jButton21.setText("Kundenberater");
    jButton21.setName("btnKundenberater"); // NOI18N
    jButton21.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton21ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton21);

    jButton22.setText("Flugpersonal");
    jButton22.setToolTipText("");
    jButton22.setName("btnFlugpersonal"); // NOI18N
    jButton22.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton22ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton22);

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Flugzeuge");
    jPanel5.add(jLabel3);

    jButton24.setText("Triebwerkart");
    jButton24.setName("btnTriebwerkart"); // NOI18N
    jButton24.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton24ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton24);

    jButton25.setText("Flugzeugtyp");
    jButton25.setName("btnFlugzeugtyp"); // NOI18N
    jButton25.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton25ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton25);

    jButton26.setText("Flugzeug");
    jButton26.setName("btnFlugzeug"); // NOI18N
    jButton26.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton26ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton26);

    jButton27.setText("Flugzeugkosten");
    jButton27.setToolTipText("");
    jButton27.setName("btnFlugkosten"); // NOI18N
    jButton27.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton27ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton27);

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Kunden");
    jPanel5.add(jLabel4);

    jButton28.setText("Kunde");
    jButton28.setName("btnKunde"); // NOI18N
    jButton28.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton28ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton28);

    jButton29.setLabel("Kundemitarbeiter");
    jButton29.setName("btnKundemitarbeiter"); // NOI18N
    jButton29.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton29ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton29);

    jButton30.setText("Zahlungsbedingungen");
    jButton30.setName("btnZahlungsbedingung"); // NOI18N
    jButton30.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton30ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton30);

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Administration");
    jPanel5.add(jLabel5);

    jButton31.setText("Benutzergruppe");
    jButton31.setName("btnBenutzergruppe"); // NOI18N
    jButton31.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton31ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton31);

    jButton32.setText("Benutzer");
    jButton32.setName("btnBenutzer"); // NOI18N
    jButton32.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton32ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton32);

    jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

    jSplitPane1.setLeftComponent(jPanel2);

    jPanel3.setName("pnlFenster"); // NOI18N
    jPanel3.setLayout(new java.awt.BorderLayout());
    jSplitPane1.setRightComponent(jPanel3);

    jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

    jMenuBar1.addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentMoved(java.awt.event.ComponentEvent evt) {
        jMenuBar1ComponentMoved(evt);
      }
    });

    jMenu1.setText("Datei");
    jMenu1.setName("nmDatei"); // NOI18N

    jMenuItem1.setText("Speichern");
    jMenuItem1.setName("mntmSpeichern"); // NOI18N
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("Abbrechen");
    jMenuItem2.setName("mntmAbbrechen"); // NOI18N
    jMenu1.add(jMenuItem2);

    jMenuItem3.setText("Löschen");
    jMenuItem3.setName("mntmLoeschen"); // NOI18N
    jMenu1.add(jMenuItem3);

    jMenuItem4.setText("Aktualisieren");
    jMenuItem4.setName("mntmAktualisieren"); // NOI18N
    jMenu1.add(jMenuItem4);
    jMenu1.add(jSeparator1);

    jMenuItem5.setText("Drucken");
    jMenuItem5.setName("mntmDrucken"); // NOI18N
    jMenu1.add(jMenuItem5);
    jMenu1.add(jSeparator2);

    jMenuItem6.setText("Abmelden");
    jMenuItem6.setName("mntmAbmelden"); // NOI18N
    jMenu1.add(jMenuItem6);

    jMenuItem7.setText("Beenden");
    jMenuItem7.setName("mntmBeenden"); // NOI18N
    jMenu1.add(jMenuItem7);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Navigation");
    jMenu2.setName("mnNavigation"); // NOI18N

    jMenuItem8.setText("Suchen");
    jMenuItem8.setName("mntmSuche"); // NOI18N
    jMenu2.add(jMenuItem8);
    jMenu2.add(jSeparator3);

    jMenuItem9.setText("Erster Datensatz");
    jMenuItem9.setName("mntmErster"); // NOI18N
    jMenu2.add(jMenuItem9);

    jMenuItem10.setText("Vorheriger Datensatz");
    jMenuItem10.setName("mntmVorheriger"); // NOI18N
    jMenu2.add(jMenuItem10);

    jMenuItem11.setText("Nächster Datensatz");
    jMenuItem11.setName("mntmNaechster"); // NOI18N
    jMenu2.add(jMenuItem11);

    jMenuItem12.setText("Letzter Datensatz");
    jMenuItem12.setName("mntmLetzter"); // NOI18N
    jMenu2.add(jMenuItem12);

    jMenuBar1.add(jMenu2);

    jMenu7.setText("Extras");
    jMenu7.setName("mnExtras"); // NOI18N

    jMenu10.setText("Visualisierung");
    jMenu10.setName("mnVisualisierung"); // NOI18N

    jRadioButtonMenuItem1.setSelected(true);
    jRadioButtonMenuItem1.setText("Java Style L&F");
    jRadioButtonMenuItem1.setName("mntmJava"); // NOI18N
    jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButtonMenuItem1ActionPerformed(evt);
      }
    });
    jMenu10.add(jRadioButtonMenuItem1);

    jRadioButtonMenuItem2.setText("Motif Style L&F");
    jRadioButtonMenuItem2.setName("mntmMotiv"); // NOI18N
    jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButtonMenuItem2ActionPerformed(evt);
      }
    });
    jMenu10.add(jRadioButtonMenuItem2);

    jRadioButtonMenuItem3.setText("Windows Style L&F");
    jRadioButtonMenuItem3.setName("mntmWindows"); // NOI18N
    jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButtonMenuItem3ActionPerformed(evt);
      }
    });
    jMenu10.add(jRadioButtonMenuItem3);

    jRadioButtonMenuItem5.setText("Nimbus L&F");
    jRadioButtonMenuItem5.setName("mntmNimbus"); // NOI18N
    jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButtonMenuItem5ActionPerformed(evt);
      }
    });
    jMenu10.add(jRadioButtonMenuItem5);

    jMenu7.add(jMenu10);

    jMenuBar1.add(jMenu7);

    jMenu8.setText("?");
    jMenu8.setName("mnHilfe"); // NOI18N

    jMenuItem14.setText("Handbuch");
    jMenuItem14.setName("mntmHandbuch"); // NOI18N
    jMenu8.add(jMenuItem14);

    jMenuItem15.setText("Info");
    jMenuItem15.setName("mntmInfo"); // NOI18N
    jMenu8.add(jMenuItem15);

    jMenuBar1.add(jMenu8);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuBar1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentMoved
    // TODO add your handling code here:
  }//GEN-LAST:event_jMenuBar1ComponentMoved

  private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
		AnredeInfo anrede = new AnredeInfo();
		anrede.show( jPanel3 );
  }//GEN-LAST:event_jButton17ActionPerformed

  private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
		OrtInfo ort = new OrtInfo();
		ort.show( jPanel3 );
  }//GEN-LAST:event_jButton18ActionPerformed

  private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
		KundeInfo kunde = new KundeInfo();
		kunde.show( jPanel3 );
  }//GEN-LAST:event_jButton28ActionPerformed

  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jMenuItem1ActionPerformed

  private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
		StaatInfo staat = new StaatInfo();
		staat.show( jPanel3 );
  }//GEN-LAST:event_jButton19ActionPerformed

  private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
		FirmaInfo firma = new FirmaInfo();
		firma.show( jPanel3 );
  }//GEN-LAST:event_jButton20ActionPerformed

  private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
		KundenberaterInfo kundenberater = new KundenberaterInfo();
		kundenberater.show( jPanel3 );
  }//GEN-LAST:event_jButton21ActionPerformed

  private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
    // TODO add your handling code here:
		// Flugpersonal erfassen
  }//GEN-LAST:event_jButton22ActionPerformed

  private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
		TriebwerkartInfo triebwerkart = new TriebwerkartInfo();
		triebwerkart.show( jPanel3 );
  }//GEN-LAST:event_jButton24ActionPerformed

  private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
		FlugzeugtypInfo flugzeugtyp = new FlugzeugtypInfo();
		flugzeugtyp.show( jPanel3 );
  }//GEN-LAST:event_jButton25ActionPerformed

  private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
		FlugzeugInfo flugzeug = new FlugzeugInfo();
		flugzeug.show( jPanel3 );
  }//GEN-LAST:event_jButton26ActionPerformed

  private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
		FlugzeugkostenInfo flugzeugkosten = new FlugzeugkostenInfo();
		flugzeugkosten.show( jPanel3 );
  }//GEN-LAST:event_jButton27ActionPerformed

  private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
		MitarbkundeInfo mitarbkunde = new MitarbkundeInfo();
		mitarbkunde.show( jPanel3 );
  }//GEN-LAST:event_jButton29ActionPerformed

  private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
		ZahlungsbedingungInfo zahlungsbedingung = new ZahlungsbedingungInfo();
		zahlungsbedingung.show( jPanel3 );
  }//GEN-LAST:event_jButton30ActionPerformed

  private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
		BenutzergruppeInfo benutzergruppe = new BenutzergruppeInfo();
		benutzergruppe.show( jPanel3 );
  }//GEN-LAST:event_jButton31ActionPerformed

  private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
		BenutzerInfo benutzer = new BenutzerInfo();
		benutzer.show( jPanel3 );
  }//GEN-LAST:event_jButton32ActionPerformed

  private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
    try {  
			UIManager.setLookAndFeel(  
				"javax.swing.plaf.metal.MetalLookAndFeel"
			);
			SwingUtilities.updateComponentTreeUI( this );
			jRadioButtonMenuItem1.setSelected( true );
			jRadioButtonMenuItem2.setSelected( false );
			jRadioButtonMenuItem3.setSelected( false );
			jRadioButtonMenuItem5.setSelected( false );
		} catch( Exception e ) { 
			e.printStackTrace(); 
		}

  }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

  private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
    try {  
			UIManager.setLookAndFeel(  
				"com.sun.java.swing.plaf.motif.MotifLookAndFeel"
			);
			SwingUtilities.updateComponentTreeUI( this );
			jRadioButtonMenuItem1.setSelected( false );
			jRadioButtonMenuItem2.setSelected( true );
			jRadioButtonMenuItem3.setSelected( false );
			jRadioButtonMenuItem5.setSelected( false );
		} catch( Exception e ) { 
			e.printStackTrace(); 
		}
  }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

  private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
    try {  
			UIManager.setLookAndFeel(  
				"com.sun.java.swing.plaf.windows.WindowsLookAndFeel"
			);
			SwingUtilities.updateComponentTreeUI( this );
			jRadioButtonMenuItem1.setSelected( false );
			jRadioButtonMenuItem2.setSelected( false );
			jRadioButtonMenuItem3.setSelected( true );
			jRadioButtonMenuItem5.setSelected( false );
		} catch( Exception e ) { 
			e.printStackTrace(); 
		}
  }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

  private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
    try {  
			UIManager.setLookAndFeel(  
				"javax.swing.plaf.nimbus.NimbusLookAndFeel"
			);
			SwingUtilities.updateComponentTreeUI( this );
			jRadioButtonMenuItem1.setSelected( false );
			jRadioButtonMenuItem2.setSelected( false );
			jRadioButtonMenuItem3.setSelected( false );
			jRadioButtonMenuItem5.setSelected( true );
		} catch( Exception e ) { 
			e.printStackTrace(); 
		}
  }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] ) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
				if( "Nimbus".equals( info.getName() ) ) {
					javax.swing.UIManager.setLookAndFeel( info.getClassName() );
					break;
				}
			}
		}
		catch( ClassNotFoundException ex ) {
			java.util.logging.Logger.getLogger( FrmMain.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
		}
		catch( InstantiationException ex ) {
			java.util.logging.Logger.getLogger( FrmMain.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
		}
		catch( IllegalAccessException ex ) {
			java.util.logging.Logger.getLogger( FrmMain.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
		}
		catch( javax.swing.UnsupportedLookAndFeelException ex ) {
			java.util.logging.Logger.getLogger( FrmMain.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater( new Runnable() {
			public void run() {
				new FrmMain().setVisible( true );
			}
		} );
	}
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton12;
  private javax.swing.JButton jButton17;
  private javax.swing.JButton jButton18;
  private javax.swing.JButton jButton19;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton20;
  private javax.swing.JButton jButton21;
  private javax.swing.JButton jButton22;
  private javax.swing.JButton jButton24;
  private javax.swing.JButton jButton25;
  private javax.swing.JButton jButton26;
  private javax.swing.JButton jButton27;
  private javax.swing.JButton jButton28;
  private javax.swing.JButton jButton29;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton30;
  private javax.swing.JButton jButton31;
  private javax.swing.JButton jButton32;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu10;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenu jMenu4;
  private javax.swing.JMenu jMenu5;
  private javax.swing.JMenu jMenu6;
  private javax.swing.JMenu jMenu7;
  private javax.swing.JMenu jMenu8;
  private javax.swing.JMenu jMenu9;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuBar jMenuBar2;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem10;
  private javax.swing.JMenuItem jMenuItem11;
  private javax.swing.JMenuItem jMenuItem12;
  private javax.swing.JMenuItem jMenuItem13;
  private javax.swing.JMenuItem jMenuItem14;
  private javax.swing.JMenuItem jMenuItem15;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem6;
  private javax.swing.JMenuItem jMenuItem7;
  private javax.swing.JMenuItem jMenuItem8;
  private javax.swing.JMenuItem jMenuItem9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
  private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
  private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
  private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JPopupMenu.Separator jSeparator2;
  private javax.swing.JPopupMenu.Separator jSeparator3;
  private javax.swing.JToolBar.Separator jSeparator4;
  private javax.swing.JToolBar.Separator jSeparator5;
  private javax.swing.JToolBar.Separator jSeparator6;
  private javax.swing.JToolBar.Separator jSeparator7;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JToolBar jToolBar1;
  // End of variables declaration//GEN-END:variables
}
